CREATE TABLE IF NOT EXISTS pais (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS liga (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    pais_id INT,
    FOREIGN KEY (pais_id) REFERENCES pais(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS equipo (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(255) NOT NULL,
    liga_id INT,
    FOREIGN KEY (liga_id) REFERENCES liga(id) ON DELETE CASCADE
);
