DROP SEQUENCE EQUIPO_SEQ;

CREATE SEQUENCE EQUIPO_SEQ
START WITH 25
INCREMENT BY 1;

DROP SEQUENCE PAIS_SEQ;

CREATE SEQUENCE PAIS_SEQ
START WITH 11
INCREMENT BY 1;

DROP SEQUENCE LIGA_SEQ;

CREATE SEQUENCE LIGA_SEQ
START WITH 11
INCREMENT BY 1;